package main

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"log"
	"net/http"
	"time"
)

type BookingHandler struct {
}

type Employee struct {
	Name   string  `json:"name" xml:"name"`
	Age    int     `json:"age" xml:"age"`
	Salary float32 `json:"salary" xml:"salary"`
}

type bookingEntry struct {
	BookingId int    `json:"id"`
	GlampId   int    `json:"glampID"`
	UserID    int    `json:"userID"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	CreatedAt int    `json:"createdAt"`
}

func (h *BookingHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		name := r.FormValue("name")
		fmt.Fprintf(w, "Parsed query-param with key \"name\": %s", name)

	case http.MethodPost:
		// body, err := ioutil.ReadAll(r.Body)
		// if err != nil {
		// 	http.Error(w, "Unable to read request body", http.StatusBadRequest)
		// 	return
		// }
		// defer r.Body.Close()

		var employee Employee
		contentType := r.Header.Get("Content-Type")
		switch contentType {
		case "application/json":
			err := json.NewDecoder(r.Body).Decode(&employee)
			if err != nil {
				http.Error(w, "Unable to unmarshal JSON", http.StatusBadRequest)
				return
			}
		case "application/xml":
			err := xml.NewDecoder(r.Body).Decode(&employee)
			if err != nil {
				http.Error(w, "Unable to unmarshal XML", http.StatusBadRequest)
				return
			}

		default:
			http.Error(w, "Unknown content type", http.StatusBadRequest)
			return
		}

		fmt.Fprintf(w, "Got a new employee!\nName: %s\nAge: %dy.o.\nSalary %0.2f\n",
			employee.Name,
			employee.Age,
			employee.Salary,
		)
	}
}

/*
 * Shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
//  package main

//  import (
// 	 "log"
// 	 "net/http"

// 	 // WARNING!
// 	 // Change this to a fully-qualified import path
// 	 // once you place this file into your project.
// 	 // For example,
// 	 //
// 	 //    sw "github.com/myname/myrepo/go"
// 	 //
// 	 sw "github.com/GurovSD/tiny_booking/go"
//  )

//  func main() {
// 	 log.Printf("Server started")

// 	 router := sw.NewRouter()

// 	 go log.Fatal(http.ListenAndServe(":8080", router))
//  }

func main() {

	bookingHandler := &BookingHandler{}
	// http.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
	// 	fmt.Fprintf(w, "Hello World!")
	// })
	http.Handle("/", bookingHandler)

	srv := &http.Server{
		Addr:         ":8080",
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	log.Fatal(srv.ListenAndServe())
}
