/*
 * Shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"os"
)

type ItemsUploadImageBody struct {

	AdditionalMetadata string `json:"additionalMetadata,omitempty"`
	// file to upload
	FileName **os.File `json:"fileName,omitempty"`
}
