/*
 * Shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ItemsItemIdBody struct {
	// Updated name of the item
	Name string `json:"name,omitempty"`
	// Updated status of the item
	Status string `json:"status,omitempty"`
}
